In [5]:
import os
from pathlib import Path
import sys

import pandas as pd

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname('./'), '..')))
from ba_tools import enrich, data

data_dir = Path('./').parent/'test_data'
gdb = data_dir/'test_data.gdb'

block_groups = gdb/'block_groups'
block_group_id_field = 'ID'

In [6]:
data.enrich_vars_dataframe

,name,alias,collection_name,enrich_str,enrich_field_name
0,AGE0_CY,2019 Population Age <1,1yearincrements,1yearincrements.AGE0_CY,F1yearincrements_AGE0_CY
1,AGE1_CY,2019 Population Age 1,1yearincrements,1yearincrements.AGE1_CY,F1yearincrements_AGE1_CY
2,AGE2_CY,2019 Population Age 2,1yearincrements,1yearincrements.AGE2_CY,F1yearincrements_AGE2_CY
3,AGE3_CY,2019 Population Age 3,1yearincrements,1yearincrements.AGE3_CY,F1yearincrements_AGE3_CY
4,AGE4_CY,2019 Population Age 4,1yearincrements,1yearincrements.AGE4_CY,F1yearincrements_AGE4_CY
...,...,...,...,...,...
8211,ACSRMV1990,ACS RHHs/Moved In: 1990-1999,yearmovedin,yearmovedin.ACSRMV1990,yearmovedin_ACSRMV1990
8212,ACSRMV1980,ACS RHHs/Moved In: 1980-1989,yearmovedin,yearmovedin.ACSRMV1980,yearmovedin_ACSRMV1980
8213,ACSRMV1979,ACS RHHs/Moved In: 1979/Before,yearmovedin,yearmovedin.ACSRMV1979,yearmovedin_ACSRMV1979
8214,ACSMEDYRMV,ACS Median Year Householder Moved In,yearmovedin,yearmovedin.ACSMEDYRMV,yearmovedin_ACSMEDYRMV
8215,ACSOWNER,ACS Owner Households,yearmovedin,yearmovedin.ACSOWNER,yearmovedin_ACSOWNER